export const statisticsMilkData = [
      {
        year: 2018,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2019,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2020,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2021,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2022,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2023,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2024,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2025,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2026,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2027,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2028,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      {
        year: 2029,
        data: [
          { month: 'Jan', value: 1100 },
          { month: 'Feb', value: 5500 },
          { month: 'Mar', value: 7200 },
          { month: 'Apr', value: 8200 },
          { month: 'May', value: 8700 },
          { month: 'Jun', value: 9400 },
          { month: 'Jul', value: 6800 },
          { month: 'Aug', value: 4200 },
          { month: 'Sep', value: 8900 },
          { month: 'Oct', value: 9100 },
          { month: 'Nov', value: 9800 },
          { month: 'Dec', value: 9600 },
        ],
      },
      
  ];
  
  export default statisticsMilkData;